### ISSUE TITLE
ldap

### ISSUE THREAD

**Issue by zhouyuansheng0618** [nzlosh/st2_ldap#2]
Excuse me, can I consult you about LDAP

**Comment by nzlosh** [comment]
I'm not an LDAP consultant.  If you have a specific question in the context of using this pack, I might be able to answer your question but note that this repository has not been maintained in many years and was left as a work in progress.

**Comment by zhouyuansheng0618** [comment]
What I want to know is how is LDAP integrated in the project
Is st2auth?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nzlosh/stackstorm_ldap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nzlosh/stackstorm_ldap] ldap (Issue #2)





 
I'm not an LDAP consultant.  If you have a specific question in the context of using this pack, I might be able to answer your question but note that this repository has been maintained in many years and was left as a work in progress.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nzlosh** [comment]
The StackStorm LDAP pack has nothing to do with St2 authentication, it is a pack that let's StackStorm workflows interact with an LDAP server.

**Comment by zhouyuansheng0618** [comment]
https://docs.stackstorm.com/3.4/authentication.html#ldap
I was referring to this, but I didn't run it successfully







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nzlosh/stackstorm_ldap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nzlosh/stackstorm_ldap] ldap (Issue #2)





 
The StackStorm LDAP pack has nothing to do with St2 authentication, it is a pack that let's StackStorm workflows interact with an LDAP server.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nzlosh** [comment]
This is not the project for StackStorm authentication.

**Comment by zhouyuansheng0618** [comment]
So what do I do? Can you guide me
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nzlosh/stackstorm_ldap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nzlosh/stackstorm_ldap] ldap (Issue #2)





 
This is not the project for StackStorm authentication.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nzlosh** [comment]
Unfortunately I can not, I don't have the time.  If you need guidance, I suggest you seek profession assistance.

**Comment by zhouyuansheng0618** [comment]
ok
thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nzlosh/stackstorm_ldap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nzlosh/stackstorm_ldap] ldap (Issue #2)





 
Unfortunately I can not, I don't have the time.  If you need guidance, I suggest you seek profession assistance.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
